# Site settings
title: Page Type API
mini: Papi
abbr: wp-papi
email: fredrik.forsmo@gmail.com
description: "Papi has a different approach on how to work with fields and page types in WordPress."
baseurl: ""
url: "http://wp-ptb.github.io"

# Build settings
markdown: kramdown
permalink: /:title

# Exclude
exclude: ['node_modules/']
